version: '3'

services:
  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
